<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Ramsey\Uuid\Uuid;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'stage_name',
        'address_1',
        'address_2',
        'city',
        'state',
        'postal_code',
        'mc_acct_ref',
        'email',
        'password',
        'uuid',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function fill(array $attributes)
    {
        if (!array_has($attributes, 'uuid')) {
            $attributes['uuid'] = Uuid::uuid4();
        }
        $attributes['mc_acct_ref'] = 'ref_acct_01538931851233324970';
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }
}
